<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ftrace" nsURI="http://www.eclipse.org/m2m/atl/emftvm/ftrace"
    nsPrefix="ftrace">
  <eAnnotations source="Descrition" references="#/">
    <details key="description" value="This is a flat/compact representation of the trace metamodel &#xA;"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="FLink">
    <eAnnotations source="Descrition" references="#/">
      <details key="ruleName" value="this attribute contains the name of the matched rule"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ruleName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sources" upperBound="-1"
        eType="#//FSourceElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targets" lowerBound="1"
        upperBound="-1" eType="#//FTargetElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTraceElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runtimeObject" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FTargetElement" eSuperTypes="#//FTraceElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FSourceElement" eSuperTypes="#//FTraceElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mapsToSelf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TraceProperty">
    <eOperations name="resolveBinding">
      <eGenericType eClassifier="ecore:EDataType trace.ecore#//JavaList">
        <eTypeArguments/>
      </eGenericType>
      <eParameters name="traces">
        <eGenericType eClassifier="ecore:EDataType trace.ecore#//JavaList">
          <eTypeArguments/>
        </eGenericType>
      </eParameters>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvedFor" lowerBound="1"
        eType="#//FTargetElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="resolvings" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resolved" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="appliedAt" eType="#//FLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="JavaList" instanceClassName="java.util.List">
    <eAnnotations/>
    <eTypeParameters name="E"/>
  </eClassifiers>
</ecore:EPackage>
